[BE] Animal CRUD
bettersg/PawScore pull request #35
Opened 2021-11-10 16:44 UTC by qroll

### Changes
- Added endpoints to create/update animal records
- Modified seeders
  - Updated `user.role` property in `20211010023111-add-adopters.ts` to fit the updated schema
  - Added user with SHELTER_ADMIN role for testing

### WIP
- Image handling

2021-11-12 13:54 UTC, stonefruit requested changes

2021-11-12 14:31 UTC, qroll commented on backend/src/seeders/20210829152403-seed-shelter-example.ts
> +        roles: JSON.stringify(["SHELTER_ADMIN"]),
Tried passing in the User model and also a literal object, sadly didn't work.

Side note, the typing is off, the docs have it as `bulkInsert(tableName: string, records: Array, options: object, attributes: object)` but the actual type expects `string | string[] | undefined` for the last argument.

2021-11-12 14:43 UTC, qroll commented on backend/src/models/animal.ts
>      id: {
Fixed the mismatched model attribute, the migration and interface are otherwise correct

2021-11-12 15:55 UTC, stonefruit commented on backend/src/seeders/20210829152403-seed-shelter-example.ts
> +        roles: JSON.stringify(["SHELTER_ADMIN"]),
I see. As long as it saves in postgres as jsonb. Might need to query for certain user roles in the future from a large base of users from different places.

2021-11-20 13:44 UTC, stonefruit approved these changes

2021-11-20 13:44 UTC, merged